/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univali.computacao.animais.gui;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author 6949673
 */
public class TelaOp3 extends javax.swing.JPanel {
    BufferedImage carregaImagem;
    String caminhoBase="src\\br\\univali\\computacao\\jogo\\gui\\imagens\\";
    String arquivo = "img3.jpg";
    /**
     * Creates new form TelaOp3
     */
    public TelaOp3() {
        initComponents();
    }
    
    protected void paintComponent(Graphics g){
        super.paintComponent(g);
        
        g.drawImage(carregaImagem, 50,50, null);
        ///g.drawImage(carregaImagem, 50, 50, 50, 50, null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    public void setImagem(){
        String caminho;
        caminho=this.caminhoBase;
        caminho = this.caminhoBase+this.arquivo;
        try {
            this.carregaImagem = ImageIO.read(new File(caminho));
        } catch (IOException ex) {
            Logger.getLogger(TelaDesenho.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
